fast construction
chelate/StaticBitArrays.jl pull request #3
Opened 2021-06-22 13:39 UTC by rafaqz

Ok couldn't resist. 

This PR gives us fast type-stable constructors from arrays or tuples.

Things I learned:
- use bitshifts `<<` for creating chunks, no `mod`
- use `ntuple(M) do` blocks to define chunks

Currently this is broken for arrays that don't match the chunk size, will have to think of how to handle this without performance loss.

2021-06-22 17:11 UTC, chelate requested changes
Looks good. I think this should work with under-filled arrays before I merge it. Maybe just something like
```
if M == c  
nb =  mod(L, nbits(T))
end
for 1:nb
...
```
in the `ntuple do` block?

2021-06-22 17:38 UTC, rafaqz commented
Yeah lets fix before merge, have a go if you like.

2021-06-23 08:16 UTC, chelate approved these changes
Looks good.

Thanks for the tests and formatting as well.

2021-06-23 08:19 UTC, chelate commented
I'm a little amazed the splat is the best thing to do on line 53, always thought splatting was a little slow. Your code reminds me of the "weight weenies"-- on the trail. Hikers who cut off all the extra straps and everything, to get their pack just that much lighter :P

2021-06-23 08:22 UTC, merged

2021-06-23 10:27 UTC, rafaqz commented
I hike like that too lol, except I refuse to use a half toothbrush, that insane!!

And you may think splat is slow because splatting a vector is slow, because the length is not know at compile time. But splatting a tuple has no runtime cost, were just shuffling handles to registers around for our own understanding of the thing. There wont likely be any native code change or any actual physical thing that happens because of the splat.

I think its a few orders of magnitude faster now, so all the snipping worked ;)